### ISSUE TITLE
Server Error (500) when viewing a map

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#148]
hello,
I have uploaded a qgs project and I am seeing this error (with orange as background color):

```
Oops!
{ "readyState": 4, "responseText": "<h1>Server Error (500)</h1>", "status": 500, "statusText": "Internal Server Error" }
Al momento non è possibile caricare la mappa
```

If I do `docker logs g3w-suite-docker_g3w-suite_1`, I have this output.
It seems that there's an error from qgis server engine, where can I find its log?

```
[2020-10-01 11:59:54 +0000] [108] [DEBUG] GET /api/config/2/qdjango/3
Internal Server Error: /api/config/2/qdjango/3
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/g3w-admin/client/api/views.py", line 34, in get
    'metadata' in ps.data and \
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/code/g3w-admin/qdjango/api/projects/serializers.py", line 174, in to_representation
    ret['print'] = json.loads(clean_for_json(instance.layouts)) if instance.layouts else []
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1262 (char 1261)
Internal Server Error: /api/config/2/qdjango/3
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/g3w-admin/client/api/views.py", line 34, in get
    'metadata' in ps.data and \
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.6/dist-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/code/g3w-admin/qdjango/api/projects/serializers.py", line 174, in to_representation
    ret['print'] = json.loads(clean_for_json(instance.layouts)) if instance.layouts else []
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1262 (char 1261)
```

**Comment by wlorenzetti** [comment]
Hi @lucamanga, I know you are using _g3w-suite-docker_, so read my reply to your issue: https://github.com/g3w-suite/g3w-suite-docker/issues/15#issuecomment-702093929

Try to use last stable version v3.0.x

**Comment by lucamanga** [comment]
With the ```3.0.x``` branch, I get same error, with this backtrace log:

```
g3w-suite_1  | libpng warning: iCCP: known incorrect sRGB profile
g3w-suite_1  | libpng warning: iCCP: known incorrect sRGB profile
g3w-suite_1  | Internal Server Error: /api/config/2/qdjango/3
g3w-suite_1  | Traceback (most recent call last):
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
g3w-suite_1  |     response = get_response(request)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 145, in _get_response
g3w-suite_1  |     response = self.process_exception_by_middleware(e, request)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 143, in _get_response
g3w-suite_1  |     response = response.render()
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 106, in render
g3w-suite_1  |     self.content = self.rendered_content
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/rest_framework/response.py", line 70, in rendered_content
g3w-suite_1  |     ret = renderer.render(self.data, accepted_media_type, context)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/rest_framework/renderers.py", line 103, in render
g3w-suite_1  |     allow_nan=not self.strict, separators=separators
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/rest_framework/utils/json.py", line 25, in dumps
g3w-suite_1  |     return json.dumps(*args, **kwargs)
g3w-suite_1  |   File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
g3w-suite_1  |     **kw).encode(obj)
g3w-suite_1  |   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
g3w-suite_1  |     chunks = self.iterencode(o, _one_shot=True)
g3w-suite_1  |   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
g3w-suite_1  |     return _iterencode(o, 0)
g3w-suite_1  | ValueError: Out of range float values are not JSON compliant
g3w-suite_1  | Internal Server Error: /api/config/2/qdjango/3
g3w-suite_1  | Traceback (most recent call last):
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
g3w-suite_1  |     response = get_response(request)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 145, in _get_response
g3w-suite_1  |     response = self.process_exception_by_middleware(e, request)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 143, in _get_response
g3w-suite_1  |     response = response.render()
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/response.py", line 106, in render
g3w-suite_1  |     self.content = self.rendered_content
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/rest_framework/response.py", line 70, in rendered_content
g3w-suite_1  |     ret = renderer.render(self.data, accepted_media_type, context)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/rest_framework/renderers.py", line 103, in render
g3w-suite_1  |     allow_nan=not self.strict, separators=separators
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/rest_framework/utils/json.py", line 25, in dumps
g3w-suite_1  |     return json.dumps(*args, **kwargs)
g3w-suite_1  |   File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
g3w-suite_1  |     **kw).encode(obj)
g3w-suite_1  |   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
g3w-suite_1  |     chunks = self.iterencode(o, _one_shot=True)
g3w-suite_1  |   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
g3w-suite_1  |     return _iterencode(o, 0)
g3w-suite_1  | ValueError: Out of range float values are not JSON compliant
```

**Comment by wlorenzetti** [comment]
Hi @lucamanga your qgis project is on version 3.10?

**Comment by lucamanga** [comment]
I did these steps:

1. git pull the 3.0.x branch
1. cleaned all g3w-suite volume data to reset its state
1. loaded a qgis 3.10.5 version project
1. baaam... same error

how can I debug it to find the problem?

**Comment by lucamanga** [comment]
OK, it seems that the project was corrupted. I made a new project then I copied & pasted from the old to the new (right click on the TOC, "Copy" and  then "Paste" layers/group).
