### ISSUE TITLE
Server Error (500) adding a simple project

### ISSUE THREAD

**Issue by lucamanga** [g3w-suite/g3w-admin#149]
Hello, I'm having an error 500 after adding a simple project. Here is the traceback. Notice the **psycopg2.errors.NotNullViolation: null value in column "download_gpx" violates not-null constraint**

```
[2020-10-05 15:04:07 +0000] [123] [DEBUG] POST /it/qdjango/piano-regolatore-generale/project/add/
Logged warning: Loading a file that was saved with an older version of qgis (saved in 3.10.9-A Coru?a, loaded in 3.10.10-A Coru?a). Problems may occur.
Internal Server Error: /it/qdjango/piano-regolatore-generale/project/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
qdjango.models.projects.Layer.DoesNotExist: Layer matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "download_gpx" violates not-null constraint
DETAIL:  Failing row contains (106, Area alloggi tempo libero e vacanze, Area alloggi tempo libero e vacanze, , area-alloggi-tempo-libero-e-vacanze-2, t, postgres, dbname='prg' host=db port=5432 user='postgres' password='..., f, 0, , [{"name": "ogc_fid", "type": "INT", "label": "ogc_fid"}, {"name"..., 5, Area_alloggi_tempo_libero_e_vacanze_ddd94d36_f029_45a2_9cee_d25b..., 0, 100000000, f, 25832, null, null, Polygon, area_alloggi_tempo_libero_vacanze, null, ["area", "ogc_fid", "art_", "fumetto", "legenda", "id"], ["area", "ogc_fid", "art_", "fumetto", "legenda", "id"], [], {'ogc_fid': {'widgetv2type': 'Range', 'fieldEditable': '1', 'val..., f, null, generatedlayout, f, f, f, null, null).
```

**Comment by lucamanga** [comment]
![immagine](https://user-images.githubusercontent.com/23235179/95097093-5d968380-072d-11eb-9114-d5860deff023.png)

This is the screen.

**Comment by wlorenzetti** [comment]
Hi @lucamanga, it's strange because into v3.0.x version is not present download_gpx column. Do you use this branch?

**Comment by lucamanga** [comment]
Ok, it was my fault. I cleaned all volumes and did a git pull from 3.0.x branch. The error disappeared.
