### ISSUE TITLE
Template does not exists when activating the g3w-admin-frontend

### ISSUE THREAD

**Issue by NyakudyaA** [g3w-suite/g3w-admin#175]
Running https://github.com/g3w-suite/g3w-suite-docker and when I try to install the https://github.com/g3w-suite/g3w-admin-frontend I get the following error

```
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/backends/django.py", line 84, in reraise
g3w-suite_1  |     raise new from exc
g3w-suite_1  | django.template.exceptions.TemplateDoesNotExist: core/include/coockieconsent.html
g3w-suite_1  | Internal Server Error: /en/
g3w-suite_1  | Traceback (most recent call last):
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/backends/django.py", line 61, in render
g3w-suite_1  |     return self.template.render(context)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 171, in render
g3w-suite_1  |     return self._render(context)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
g3w-suite_1  |     return self.nodelist.render(context)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 937, in render
g3w-suite_1  |     bit = node.render_annotated(context)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 904, in render_annotated
g3w-suite_1  |     return self.render(context)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/loader_tags.py", line 176, in render
g3w-suite_1  |     template = context.template.engine.get_template(template_name)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/engine.py", line 143, in get_template
g3w-suite_1  |     template, origin = self.find_template(template_name)
g3w-suite_1  |   File "/usr/local/lib/python3.6/dist-packages/django/template/engine.py", line 129, in find_template
g3w-suite_1  |     raise TemplateDoesNotExist(name, tried=tried)
g3w-suite_1  | django.template.exceptions.TemplateDoesNotExist: core/include/coockieconsent.html
````

Is there any trick I am missing?.

**Comment by NyakudyaA** [comment]
I have another error which I will report
