### ISSUE TITLE
I'm having a bit of trouble understanding the installation and putting the g3w to work.

### ISSUE THREAD

**Issue by thiago95macedo** [g3w-suite/g3w-admin#2]
I have doubts regarding these 3 lines below, I do not know what to put exactly.

...

DATASOURCE_PATH = '<static_path_to_gis_data_source>'

...

MEDIA_ROOT = '<path_to_media_root>'

...

SESSION_COOKIE_NAME = '<unique_session_id>'

**Comment by wlorenzetti** [comment]
DATASOURCE_PATH = '<static_path_to_gis_data_source>'
It's place where g3w_suite can find filesystem gis data like shape files, raster, and spatillite db.
Important is the last directory in this path must be the same in your desktop project: 
I.e. if in your desktop QGIS project data are in ../geodata/ folder, so in your server where you deploy G3W-SUITE, you must create a folder with the same 'geodata' name where to put data.

MEDIA_ROOT = '<path_to_media_root>'
It's absolute filesystem path where Django application will save media that you'll upload by G3W-SUITE like images, and QGIS Project files.

SESSION_COOKIE_NAME = '<unique_session_id>'
A unique key string,  you can choose for G3W-SUITE authentication ssystem.

Very soon a better clear manual!

**Comment by thiago95macedo** [comment]
adax@srv2:~/g3w-suite/g3w-admin$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/local/lib/python3.5/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.5/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/adax/g3w-suite/g3w-admin/usersmanage/models.py", line 5, in <module>
    from core.utils.models import G3WChoices
  File "/home/adax/g3w-suite/g3w-admin/core/utils/models.py", line 6, in <module>
    from qdjango.utils.structure import datasource2dict, get_schema_table
  File "/home/adax/g3w-suite/g3w-admin/qdjango/utils/structure.py", line 15, in <module>
    from urlparse import urlsplit, parse_qs
ImportError: No module named 'urlparse'

**Comment by thiago95macedo** [comment]
adax@srv2:~/g3w-suite/g3w-admin$ python3 manage.py flush
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/adax/.local/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: invalid port number: "<5432>"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/flush.py", line 54, in handle
    allow_cascade=allow_cascade)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/sql.py", line 15, in sql_flush
    tables = connection.introspection.django_table_names(only_existing=True, include_views=False)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/introspection.py", line 86, in django_table_names
    existing_tables = self.table_names(include_views=include_views)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/introspection.py", line 53, in table_names
    with self.connection.cursor() as cursor:
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/adax/.local/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: invalid port number: "<5432>"

**Comment by wlorenzetti** [comment]
Hi Thiago,
two things:
1) G3W-SUITE for now is only for Python 2, I look at your logs and I saw you are using Python 3
2) **django.db.utils.OperationalError: invalid port number: "<5432>"**, in G3W-SUITE instructions the notations "<>" are used to indicate a variabile to replace with a value, so in this case become 'PORT': '5432'.

I hope this can help
W

**Comment by thiago95macedo** [comment]
.venv-g3w) adax@srv:~/g3wsuite/g3w-admin/g3w-admin$ python manage.py runserver
Performing system checks...

**# System check identified no issues (0 silenced).**
June 01, 2018 - 05:02:10
Django version 1.11.2, using settings 'base.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
