### ISSUE TITLE
When uploading a project file using ArcGIS Map Server layers I get this error: Error when uploading: [Project error on layers]-- [Layer error on layerType]-- Missing or invalid type for layer "arcgismapserver"

### ISSUE THREAD

**Issue by elpaso** [g3w-suite/g3w-admin#26]
Reported by customer

**Comment by elpaso** [comment]
same issue with "arcgisfetureserver"

**Comment by timlinux** [comment]
We were testing here with some XYZ layers, shapefiles etc. and whatever we do we get similar errors when trying to upload layers.:

```python
xception: [ error on metadata]-- 'NoneType' object has no attribute 'text'
ERROR 2020-01-30 09:56:29,383 exception 15 139706742368128 Internal Server Error: /api/config/3/qdjango/5
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "./client/api/views.py", line 40, in get
    elif 'onlineresource' in ps.data['metadata']:
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 534, in data
    ret = super(Serializer, self).data
  File "/usr/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 263, in data
    self._data = self.to_representation(self.instance)
  File "./qdjango/api/serializers.py", line 135, in to_representation
    qgis_projectsettings_wms = self.get_qgis_projectsettings_wms(instance)
  File "./qdjango/api/serializers.py", line 72, in get_qgis_projectsettings_wms
    return QgisProjectSettingsWMS(response.content)
  File "./qdjango/utils/data.py", line 944, in __init__
    self.setData()
  File "./core/utils/data.py", line 25, in setData
    .format(self._pre_exception_message, data, e))
Exception: [ error on metadata]-- 'NoneType' object has no attribute 'text'
```

![project-error](https://user-images.githubusercontent.com/178003/73447248-372a7800-4356-11ea-9d63-f4d47c1e6169.png)

CC @nyakudyaa and @meomancer

**Comment by timlinux** [comment]
Sometimes it is a WFS error, sometimes WMS and sometimes layerTree

**Comment by wlorenzetti** [comment]
Hi @timlinux some questions:
1.  what branch are you using? I sugget to use `dev` for Py3 and Dj2.2 or branch  `py2` for Py2 and Dj 1.11
2.  What QGIS-server version are you using? We decide to support current LTR so QGIS 3.14.
