### ISSUE TITLE
ModuleNotFoundError: No module named 'bx_py_utils.models' building v 3.2.x

### ISSUE THREAD

**Issue by duke3rd** [g3w-suite/g3w-admin#288]
Hi all, after successful docker instance I am trying to compile your amazing work on Ubuntu 20.04
v 3.1.x compiles and runs fine, v 3.2.x gives an error:

```
...
---> pavement.sync
python g3w-admin/manage.py migrate --noinput
Application path not initialized
Traceback (most recent call last):
  File "g3w-admin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.8/site-packages/huey_monitor/models.py", line 4, in <module>
    from bx_py_utils.models.timetracking import TimetrackingBaseModel
ModuleNotFoundError: No module named 'bx_py_utils.models'
...
```

Could you please help me?
Am I missing something?
Best,
duke3rd

**Comment by wlorenzetti** [comment]
Hi @duke3rd, after your issue I checked it and I found  the cause, this problem is done to new pip auto import dependence policy. So  I fix it splitting requirements into two files: `requirements.txt` and `requirements_huey.txt`.

To work fine you to install _requirements.txt_ before _requirements_huey.txt_.

I saw that you are using pavement system, I'll update that very soon.

For database compatibility from v.3.1.x to v.3.2.x you have to run db scripts: https://github.com/g3w-suite/g3w-admin/tree/v.3.2.x/db_scripts. Before and after version upgrade.

**Comment by wlorenzetti** [comment]
@duke3rd i update requirements and paver pavament.py script, try now and said me if it works.

**Comment by duke3rd** [comment]
> @duke3rd i update requirements and paver pavament.py script, try now and said me if it works.

@wlorenzetti everything is fine now, works like a charm!
thank you very much,
best regards
