### ISSUE TITLE
Error after - Paver install

### ISSUE THREAD

**Issue by nstoykov** [g3w-suite/g3w-admin#38]
Hi, I have a problem.
After entering the command: `paver install`

I get to the result:

```
ImportError: cannot import name Celery
```

I'm in a virtualenv.
Do you have any solution to the problem ???

```log
======= part of the code ==========

---> pavement.sync

python g3w-admin/manage.py migrate --noinput
Traceback (most recent call last):
  File "g3w-admin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.environments/g3wsuite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/root/.environments/g3wsuite/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/root/.environments/g3wsuite/local/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/root/.environments/g3wsuite/local/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.environments/g3wsuite/local/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mandarb/g3wsuite/g3w-admin/g3w-admin/base/__init__.py", line 4, in <module>
    from .celery import app as celery_app
  File "/home/mandarb/g3wsuite/g3w-admin/g3w-admin/base/celery.py", line 4, in <module>
    from celery import Celery
ImportError: cannot import name Celery

Captured Task Output:
---> pavement.install
---> pavement.install_yarn_components
Installing Yarn/Bower components...
yarn --ignore-engines --ignore-scripts --prod
node -e "try { require('fs').symlinkSync(require('path').resolve('node_modules/@bower_components'), 'g3w-admin/core/static/bower_components', 'junction') } catch (e) { }"
Yarn/Bower components installed.
---> pavement.requirements
Installing Python modules...
pip install -r requirements.txt
Python modules installed.
---> pavement.sync
python g3w-admin/manage.py migrate --noinput

Build failed running pavement.install: Subprocess return code: 1
```

**Comment by wlorenzetti** [comment]
Hi Nike, did you try to use dev branch?
Dev branch is migrating to Python 3 Django 2.2, but working is not complete.
I suggest to use branch py2


In data 4 Gennaio 2020 03:21:04 NIke Master <notifications@github.com> ha 
scritto:

**Comment by nstoykov** [comment]
branch py2 is for Ubuntu version 16.04 right ??

**Comment by wlorenzetti** [comment]
Yes. If you type pip freeze into your virtualenv, do you find 'celery' package?


In data 5 Gennaio 2020 02:40:33 NIke Master <notifications@github.com> ha 
scritto:

**Comment by wlorenzetti** [comment]
On my laptop I've Ubuntu 16.04. I just tried a new installation of py2 branch with paver and it every tasks was done.
Could you write your procedure?

**Comment by nstoykov** [comment]
Thanks for your help. I go on!
