### ISSUE TITLE
"paver install" fails with ModuleNotFoundError

### ISSUE THREAD

**Issue by immanuel-h** [g3w-suite/g3w-admin#419]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

"paver install" fails with ModuleNotFoundError

```
python g3w-admin/manage.py migrate --noinput
Traceback (most recent call last):
  File "g3w-admin/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/g3w/virtualenvs/g3wsuite/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/g3w/virtualenvs/g3wsuite/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/g3w/virtualenvs/g3wsuite/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/g3w/virtualenvs/g3wsuite/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/g3w/virtualenvs/g3wsuite/lib/python3.6/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/g3w/g3w-admin-dev/g3w-admin/qdjango/apps.py", line 12, in <module>
    from qgis.core import QgsApplication, QgsProject, QgsPathResolver
ModuleNotFoundError: No module named 'qgis'
```

### Steps to reproduce

Follow the instructions at https://g3w-suite.readthedocs.io/en/latest/install.html on a fresh system

### Environment

- g3w-admin: latest
- g3w-client: none
- browser: irrelevant
- operating system: Ubuntu 18.04

**Comment by Raruto** [comment]
Hi @immanuel-h 

Thanks for the report,

please update the **`Environment`** section above indicating clearly which version you are using (e.g. `g3w-admin: v3.5, v3.4, v3.3, ..`), otherwise the report is completely useless.

---

As for the error you get:

```py
File "/home/g3w/g3w-admin-dev/g3w-admin/qdjango/apps.py", line 12, in <module>
from qgis.core import QgsApplication, QgsProject, QgsPathResolver

ModuleNotFoundError: No module named 'qgis'
```

The `qgis` package is most likely not installed on your development host.

I don't think it's mentioned anywhere in the documentation, but I think the commands you need to use to install it should be more or less these:

https://github.com/g3w-suite/g3w-admin/blob/8cfa70ebc99681b3ccb0e521bfc8cbc0de3882b1/ci_scripts/Dockerfile.322.deps#L26-L30

_Have a nice day,
Raruto_

**Comment by immanuel-h** [comment]
Hi, "latest" = dev branch from Nov 29th (other admin just fetched the zip or I would give you a more exact commit hash). 

Sadly installing qgis as described did not change the situation. My impression is that paver-install ignores global libraries when run inside a venv (after all we create one in the instructions - only makes sense to assume it should be used), but running outside of the env leads to different errors (in this case, FileNotFoundError while installing bx_py_utils from some git repo) as part of requirements_huey.txt

**Comment by immanuel-h** [comment]
Actually most likely the guide is simply waaaaay outdated, because it refers to using Python 3.6, which supposedly was last supported in 3.3, so I think I'll just disregard all "guides" and do a proper fresh setup.

**Comment by wlorenzetti** [comment]
Hi @immanuel-h, as you can look at online manual (https://g3w-suite.readthedocs.io/en/latest/install.html#virtualenv-creation) 

> to use QGIS API into a virtualenv only solution is to give access python system site-packages to it using –system-site-packages option

On creation for a virtualenv you have to use the option `–system-site-packages` to use QGIS API

**Comment by immanuel-h** [comment]
I actually am using mkvirtualenv though ... as I said, followed the guide exactly. It has issues.

**Comment by wlorenzetti** [comment]
@immanuel-h I just update the online documentation: https://g3w-suite.readthedocs.io/en/latest/install.html

**Comment by immanuel-h** [comment]
Hi, sorry for the late feedback. Tried last week with the new guide and it went through without issues. It's very clear and easy to follow. Thanks for all the effort :)
