### ISSUE TITLE
For Layer constraint is necessary fillte lqdjango layers by 'project' and 'qgis_layer_id'

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin#65]
@elpaso With 2 or more projects with layers having same `qgis_layer_id` I get this exception:
```
Traceback (most recent call last):
  File "/home/walter/PycharmProjects/g3w_suite_qgis_api/g3w-admin/qdjango/server_filters/accesscontrol/constraints.py", line 28, in layerFilterSubsetString
    rule = ConstraintSubsetStringRule.get_rule_definition_for_user(QGS_SERVER.user, layer.id())
  File "/home/walter/PycharmProjects/g3w_suite_qgis_api/g3w-admin/qdjango/models/constraints.py", line 177, in get_rule_definition_for_user
    constraints = SingleLayerConstraint.objects.filter(layer=Layer.objects.get(qgs_layer_id=qgs_layer_id), active=True)
  File "/home/envs/g3w_suite_qgis_api/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/envs/g3w_suite_qgis_api/lib/python3.6/site-packages/django/db/models/query.py", line 412, in get
    (self.model._meta.object_name, num)
qdjango.models.projects.MultipleObjectsReturned: get() returned more than one Layer -- it returned 2!
```

**Comment by wlorenzetti** [comment]
@elpaso with last commit https://github.com/g3w-suite/g3w-admin/pull/39/commits/035325dd5ea788c2345dee2052721c2b1f49799e, the bug is not fixed.
