### ISSUE TITLE
Upgrading docker from 3.6.x to 3.7.x error 500 when clicking on groups tab

### ISSUE THREAD

**Issue by tudorbarascu** [g3w-suite/g3w-admin#681]
### Checklist

- [ ] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-admin/issues) and this bug has never been reported before

### Subject of the issue

Upgrading from 3.6.x to 3.7.x branch (docker) gives 500 Error on Groups tabs.

### Steps to reproduce

Upgrade to 3.7.x branch. The groups tab gives 500 ERROR.

### Environment

- g3w-admin: __version__
- g3w-client: __version__
- browser: __name__
- operating system: __name and version (desktop or mobile)__

### Additional info

```
g3w-1  | [2023-12-03 10:50:00 +0000] [86] [DEBUG] GET /en/groups/
g3w_crayfish-postgis-1    | 2023-12-03 10:50:00.591 UTC [201] g3wsuite@g3wsuite ERROR:  column qdjango_project.wms_getmap_format does not exist at character 1662
g3w_crayfish-postgis-1    | 2023-12-03 10:50:00.591 UTC [201] g3wsuite@g3wsuite STATEMENT:  SELECT "qdjango_project"."id", "qdjango_project"."created", "qdjango_project"."modified", "qdjango_project"."qgis_file", "qdjango_project"."title", "qdjango_project"."title_ur", "qdjango_project"."title_ur_it", "qdjango_project"."title_ur_en", "qdjango_project"."title_ur_fr", "qdjango_project"."title_ur_fi", "qdjango_project"."title_ur_se", "qdjango_project"."title_ur_ro", "qdjango_project"."title_ur_de", "qdjango_project"."description", "qdjango_project"."description_it", "qdjango_project"."description_en", "qdjango_project"."description_fr", "qdjango_project"."description_fi", "qdjango_project"."description_se", "qdjango_project"."description_ro", "qdjango_project"."description_de", "qdjango_project"."slug", "qdjango_project"."is_active", "qdjango_project"."thumbnail", "qdjango_project"."group_id", "qdjango_project"."initial_extent", "qdjango_project"."max_extent", "qdjango_project"."qgis_version", "qdjango_project"."layers_tree", "qdjango_project"."baselayer_id", "qdjango_project"."relations", "qdjango_project"."wms_use_layer_ids", "qdjango_project"."original_name", "qdjango_project"."feature_count_wms", "qdjango_project"."multilayer_query", "qdjango_project"."multilayer_querybybbox", "qdjango_project"."multilayer_querybypolygon", "qdjango_project"."context_base_legend", "qdjango_project"."toc_tab_default", "qdjango_project"."toc_layers_init_status", "qdjango_project"."toc_themes_init_status", "qdjango_project"."legend_position", "qdjango_project"."autozoom_query", "qdjango_project"."layouts", "qdjango_project"."use_map_extent_as_init_extent", "qdjango_project"."is_dirty", "qdjango_project"."is_locked", "qdjango_project"."order", "qdjango_project"."wms_getmap_format", "qdjango_project"."geocoding_providers" FROM "qdjango_project" WHERE ("qdjango_project"."group_id" = 1 AND "qdjango_project"."is_active")
g3w-1  | Internal Server Error: /en/groups/
g3w-1  | Traceback (most recent call last):
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
g3w-1  |     return self.cursor.execute(sql, params)
g3w-1  | psycopg2.errors.UndefinedColumn: column qdjango_project.wms_getmap_format does not exist
g3w-1  | LINE 1: ..._project"."is_locked", "qdjango_project"."order", "qdjango_p...
g3w-1  |                                                              ^
g3w-1  | 
g3w-1  | 
g3w-1  | The above exception was the direct cause of the following exception:
g3w-1  | 
g3w-1  | Traceback (most recent call last):
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
g3w-1  |     response = get_response(request)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 204, in _get_response
g3w-1  |     response = response.render()
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/response.py", line 105, in render
g3w-1  |     self.content = self.rendered_content
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/response.py", line 83, in rendered_content
g3w-1  |     return template.render(context, self._request)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/backends/django.py", line 61, in render
g3w-1  |     return self.template.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 170, in render
g3w-1  |     return self._render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 162, in _render
g3w-1  |     return self.nodelist.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
g3w-1  |     bit = node.render_annotated(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
g3w-1  |     return self.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 150, in render
g3w-1  |     return compiled_parent._render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 162, in _render
g3w-1  |     return self.nodelist.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
g3w-1  |     bit = node.render_annotated(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
g3w-1  |     return self.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 62, in render
g3w-1  |     result = block.nodelist.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
g3w-1  |     bit = node.render_annotated(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
g3w-1  |     return self.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/loader_tags.py", line 62, in render
g3w-1  |     result = block.nodelist.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 938, in render
g3w-1  |     bit = node.render_annotated(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
g3w-1  |     return self.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/defaulttags.py", line 214, in render
g3w-1  |     nodelist.append(node.render_annotated(context))
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/base.py", line 905, in render_annotated
g3w-1  |     return self.render(context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/template/library.py", line 192, in render
g3w-1  |     output = self.func(*resolved_args, **resolved_kwargs)
g3w-1  |   File "/code/g3w-admin/core/templatetags/g3wadmin_tags.py", line 140, in g3wadmin_get_projects_number
g3w-1  |     return group.getProjectsNumber(user, is_active)
g3w-1  |   File "/code/g3w-admin/core/models.py", line 219, in getProjectsNumber
g3w-1  |     groupProjects += len(qs)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 262, in __len__
g3w-1  |     self._fetch_all()
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1324, in _fetch_all
g3w-1  |     self._result_cache = list(self._iterable_class(self))
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 51, in __iter__
g3w-1  |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
g3w-1  |     cursor.execute(sql, params)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 66, in execute
g3w-1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
g3w-1  |     return executor(sql, params, many, context)
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 79, in _execute
g3w-1  |     with self.db.wrap_database_errors:
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 90, in __exit__
g3w-1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
g3w-1  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
g3w-1  |     return self.cursor.execute(sql, params)
g3w-1  | django.db.utils.ProgrammingError: column qdjango_project.wms_getmap_format does not exist
g3w-1  | LINE 1: ..._project"."is_locked", "qdjango_project"."order", "qdjango_p...
```

**Comment by tudorbarascu** [comment]
```
g3w  |   File "/code/g3w-admin/manage.py", line 10, in <module>
g3w  |     execute_from_command_line(sys.argv)
g3w  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
g3w  |     utility.execute()
g3w  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 413, in execute
g3w  |     self.fetch_command(subcommand).run_from_argv(self.argv)
g3w  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 354, in run_from_argv
g3w  |     self.execute(*args, **cmd_options)
g3w  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 398, in execute
g3w  |     output = self.handle(*args, **options)
g3w  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 89, in wrapped
g3w  |     res = handle_func(*args, **kwargs)
g3w  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 95, in handle
g3w  |     executor.loader.check_consistent_history(connection)
g3w  |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 306, in check_consistent_history
g3w  |     raise InconsistentMigrationHistory(
g3w  | django.db.migrations.exceptions.InconsistentMigrationHistory: Migration qdjango.0110_sessiontokenfilterlayer_name is applied before its dependency qdjango.0109_project_wms_getmap_format on database 'default'.```

**Comment by wlorenzetti** [comment]
Hi @tudorbarascu do you trying the https://github.com/g3w-suite/g3w-admin/tree/v.3.7.x branch? Currently we are at v3.7.0-beta.1 version.

**Comment by wlorenzetti** [comment]
What exactly was your workflow in the update?

**Comment by wlorenzetti** [comment]
Reading about you error on migrations, I think you are applying the migrations not starting from a v3.6.x  but from an intermediate branch version dev, is correct?

**Comment by tudorbarascu** [comment]
> Reading about you error on migrations, I think you are applying the migrations not starting from a v3.6.x but from an intermediate branch version dev, is correct?

Hello! Thank you! yes! That's correct. I tested with a dev version before it got branched. Then I got to 3.6 again and upgraded to 3.7. Hmm.. I'll try and apply the migrations manually.

Now that I'm rechecking I did both an upgrade from 3.6.x and a dev before branching. Will retest

**Comment by tudorbarascu** [comment]
> What exactly was your workflow in the update?

- `docker-compose down`
- did a `git checkout` on the v3.7.x branch, build the docker with

```
docker build -f Dockerfile.g3wsuite-deps.ltr.dockerfile -t g3wsuite/g3w-suite-deps-ltr:v3.7.x --no-cache . && 
docker build --build-arg G3W_SUITE_BRANCH=v.3.7.x -f Dockerfile.g3wsuite.dockerfile -t g3wsuite/g3w-suite:v3.7.x --no-cache .
```

- edited the  `docker-compose.yml` to start with the 3.7.x branch
- `docker-compose up`

**Comment by wlorenzetti** [comment]
Ok but as I wrote above, I think your migrations db table is corrupt. Please write here your django_migrations table rows list.

**Comment by tudorbarascu** [comment]
Indeed, I upgraded from a clean 3.6.x branch and it all worked perfectly. This is the migrations table on the problematic side.

```
 261 | qdjango             | 0104_set_is_active_true                           | 2023-08-10 14:02:37.40225+00
 262 | qdjango             | 0105_message                                      | 2023-08-10 14:02:37.424502+00
 263 | qdjango             | 0106_message_order                                | 2023-08-10 14:02:37.432131+00
 264 | qdjango             | 0107_auto_20230516_0806                           | 2023-08-10 14:02:37.631807+00
 265 | qdjango             | 0108_alter_layer_slug                             | 2023-08-10 14:02:37.65087+00
 284 | core                | 0082_generalsuitedata_registration_intro          | 2023-11-13 13:09:35.892062+00
 285 | core                | 0083_auto_20230921_0949                           | 2023-11-13 13:09:35.915312+00
 286 | django_registration | 0001_initial                                      | 2023-11-13 13:09:35.938419+00
 287 | qdjango             | 0109_filterlayersaved                             | 2023-11-13 13:09:35.969676+00
 288 | qdjango             | 0110_sessiontokenfilterlayer_name                 | 2023-11-13 13:09:35.979149+00
 289 | qdjango             | 0111_alter_sessiontokenfilterlayer_name           | 2023-11-13 13:09:35.988712+00
 290 | qdjango             | 0112_auto_20231017_0752                           | 2023-11-13 13:09:36.01084+00
 291 | qdjango             | 0113_auto_20231019_1237                           | 2023-11-13 13:09:36.095802+00
 292 | qdjango             | 0114_alter_sessiontokenfilter_token               | 2023-11-13 13:09:36.10541+00
 293 | usersmanage         | 0012_userdata_other_info                          | 2023-11-13 13:09:36.114703+00
 294 | usersmanage         | 0013_auto_20230922_0815                           | 2023-11-13 13:09:36.130747+00
 295 | usersmanage         | 0014_userdata_change_password_first_login         | 2023-11-13 13:09:36.139954+00
 296 | qdjango             | 0115_alter_layer_layer_type                       | 2023-11-15 10:23:04.686849+00
 297 | qdjango             | 0115_project_geocoding_providers                  | 2023-11-24 11:38:10.552119+00```

**Comment by tudorbarascu** [comment]
I've applied the ``0109_project_wms_getmap_format`` migration manually and it now works. Thanks. Sorry for the noise.

**Comment by wlorenzetti** [comment]
Don't worry, sorry for delay to reply but it's the same thing I would have written to you :)
